//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVVenues.Veni.VenueControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VenueControlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VenueControlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIVVenues.Veni.VenueControl.VenueControlStrings", typeof(VenueControlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a set biweekly/monthly schedule.
        /// </summary>
        internal static string AnswerHasBiweeklySchedule {
            get {
                return ResourceManager.GetString("AnswerHasBiweeklySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, we don&apos;t have a set schedule.
        /// </summary>
        internal static string AnswerHasNoSchedule {
            get {
                return ResourceManager.GetString("AnswerHasNoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, we have a set weekly schedule.
        /// </summary>
        internal static string AnswerHasWeeklySchedule {
            get {
                return ResourceManager.GetString("AnswerHasWeeklySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **close**?
        ///`(example: 6:30pm, 9pm or 1:30am)`.
        /// </summary>
        internal static string AskForCloseTimeDirectMessage {
            get {
                return ResourceManager.GetString("AskForCloseTimeDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **close**?
        ///`(examples: @Veni Ki 6:30pm or @Veni Ki 9pm)`.
        /// </summary>
        internal static string AskForCloseTimeMessage {
            get {
                return ResourceManager.GetString("AskForCloseTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **close** on **{0}**?
        ///`(example: 6:30pm, 9pm or 1:30am)`.
        /// </summary>
        internal static string AskForCloseTimeOnDayDirectMessage {
            get {
                return ResourceManager.GetString("AskForCloseTimeOnDayDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **close** on **{0}**?
        ///`(examples: @Veni Ki 6:30pm or @Veni Ki 9pm)`.
        /// </summary>
        internal static string AskForCloseTimeOnDayMessage {
            get {
                return ResourceManager.GetString("AskForCloseTimeOnDayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you give me an ad or **description** of the venue? Something for players to read when they click on your venue..
        /// </summary>
        internal static string AskForDescriptionDirectMessage {
            get {
                return ResourceManager.GetString("AskForDescriptionDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you give me an ad or **description** of the venue? Something for players to read when they click on your venue.
        ///`(example: @Veni Ki Veni&apos;s Mainframe is the premiere party location...)`.
        /// </summary>
        internal static string AskForDescriptionMessage {
            get {
                return ResourceManager.GetString("AskForDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicuu! 💕 What&apos;s the **SyncShell ID/Alias**?.
        /// </summary>
        internal static string AskForMareIdDirectMessage {
            get {
                return ResourceManager.GetString("AskForMareIdDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicuu! 💕 What&apos;s the **SyncShell ID/Alias**?
        ///`(example: @Veni Ki MSS-123456789ABC)`.
        /// </summary>
        internal static string AskForMareIdMessage {
            get {
                return ResourceManager.GetString("AskForMareIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and the **SyncShell password**? .
        /// </summary>
        internal static string AskForMarePasswordDirectMessage {
            get {
                return ResourceManager.GetString("AskForMarePasswordDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and the **SyncShell password**? 
        ///`(example: @Veni Ki MyV3nu3SyncShell)`.
        /// </summary>
        internal static string AskForMarePasswordMessage {
            get {
                return ResourceManager.GetString("AskForMarePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, what is the **name**? 🙂.
        /// </summary>
        internal static string AskForNameDirectMessage {
            get {
                return ResourceManager.GetString("AskForNameDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, what is the **name**? 🙂
        ///`(example: @Veni Ki Veni&apos;s Mainframe)`.
        /// </summary>
        internal static string AskForNameMessage {
            get {
                return ResourceManager.GetString("AskForNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **open**?
        ///`(example: 6:30pm, 9pm or 1:30am)`.
        /// </summary>
        internal static string AskForOpenTimeDirectMessage {
            get {
                return ResourceManager.GetString("AskForOpenTimeDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **open**?
        ///`(examples: @Veni Ki 6:30pm or @Veni Ki 9pm)`.
        /// </summary>
        internal static string AskForOpenTimeMessage {
            get {
                return ResourceManager.GetString("AskForOpenTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **open** on **{0}**?
        ///`(example: 6:30pm, 9pm or 1:30am)`.
        /// </summary>
        internal static string AskForOpenTimeOnDayDirectMessage {
            get {
                return ResourceManager.GetString("AskForOpenTimeOnDayDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **open** on **{0}**?
        ///`(examples: @Veni Ki 6:30pm or @Veni Ki 9pm)`.
        /// </summary>
        internal static string AskForOpenTimeOnDayMessage {
            get {
                return ResourceManager.GetString("AskForOpenTimeOnDayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your venue have a public **Mare SyncShell**?.
        /// </summary>
        internal static string AskIfHasMareMessage {
            get {
                return ResourceManager.GetString("AskIfHasMareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oki! Do you have a weekly opening schedule?.
        /// </summary>
        internal static string AskIfHasSchedule {
            get {
                return ResourceManager.GetString("AskIfHasSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! Let me know if you need anything. 💕 .
        /// </summary>
        internal static string Dismissed {
            get {
                return ResourceManager.GetString("Dismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaaah. You&apos;ll need to [create a ticket](https://discord.com/channels/942536163959406632/1188579990271434883) in the FFXIV Venues discord to change this part of your venue information. 😊.
        /// </summary>
        internal static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! ⚠️ After you&apos;ve saved your venue you&apos;ll need to create a ticket in our discord server and speak to our staff to set that up for you..
        /// </summary>
        internal static string RespondContactStaffForBiweekly {
            get {
                return ResourceManager.GetString("RespondContactStaffForBiweekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which venue would you like to edit? 🤔.
        /// </summary>
        internal static string SelectVenueToEdit {
            get {
                return ResourceManager.GetString("SelectVenueToEdit", resourceCulture);
            }
        }
    }
}
