//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVVenues.Veni.VenueControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VenueControlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VenueControlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIVVenues.Veni.VenueControl.VenueControlStrings", typeof(VenueControlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **close**?
        ///`(example: 6:30pm, 9pm or 1:30am)`.
        /// </summary>
        internal static string AskForCloseTimeDirectMessage {
            get {
                return ResourceManager.GetString("AskForCloseTimeDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **close**?
        ///`(examples: @Veni Ki 6:30pm or @Veni Ki 9pm)`.
        /// </summary>
        internal static string AskForCloseTimeMessage {
            get {
                return ResourceManager.GetString("AskForCloseTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **close** on **{0}**?
        ///`(example: 6:30pm, 9pm or 1:30am)`.
        /// </summary>
        internal static string AskForCloseTimeOnDayDirectMessage {
            get {
                return ResourceManager.GetString("AskForCloseTimeOnDayDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **close** on **{0}**?
        ///`(examples: @Veni Ki 6:30pm or @Veni Ki 9pm)`.
        /// </summary>
        internal static string AskForCloseTimeOnDayMessage {
            get {
                return ResourceManager.GetString("AskForCloseTimeOnDayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What **timezone** is the closing in?.
        /// </summary>
        internal static string AskForClosingTimeZone {
            get {
                return ResourceManager.GetString("AskForClosingTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! Which closure do you wish to cancel? 🥰.
        /// </summary>
        internal static string AskForClosureToCancel {
            get {
                return ResourceManager.GetString("AskForClosureToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When is your next **{0}** opening?.
        /// </summary>
        internal static string AskForCommencementMessage {
            get {
                return ResourceManager.GetString("AskForCommencementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oki, what **day** is this closing from?.
        /// </summary>
        internal static string AskForDayOfClosing {
            get {
                return ResourceManager.GetString("AskForDayOfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What **day** is this opening from? 🥰.
        /// </summary>
        internal static string AskForDayOfOpening {
            get {
                return ResourceManager.GetString("AskForDayOfOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you give me an ad or **description** of the venue? Something for players to read when they click on your venue..
        /// </summary>
        internal static string AskForDescriptionDirectMessage {
            get {
                return ResourceManager.GetString("AskForDescriptionDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you give me an ad or **description** of the venue? Something for players to read when they click on your venue.
        ///`(example: @Veni Ki Veni&apos;s Mainframe is the premiere party location...)`.
        /// </summary>
        internal static string AskForDescriptionMessage {
            get {
                return ResourceManager.GetString("AskForDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And how long are we closing for? 🥹.
        /// </summary>
        internal static string AskForHowLongClosingFor {
            get {
                return ResourceManager.GetString("AskForHowLongClosingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay, how long are we opening for? 🥰.
        /// </summary>
        internal static string AskForHowLongOpeningFor {
            get {
                return ResourceManager.GetString("AskForHowLongOpeningFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicuu! 💕 What&apos;s the **SyncShell ID/Alias**?.
        /// </summary>
        internal static string AskForMareIdDirectMessage {
            get {
                return ResourceManager.GetString("AskForMareIdDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicuu! 💕 What&apos;s the **SyncShell ID/Alias**?
        ///`(example: @Veni Ki MSS-123456789ABC)`.
        /// </summary>
        internal static string AskForMareIdMessage {
            get {
                return ResourceManager.GetString("AskForMareIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and the **SyncShell password**? .
        /// </summary>
        internal static string AskForMarePasswordDirectMessage {
            get {
                return ResourceManager.GetString("AskForMarePasswordDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and the **SyncShell password**? 
        ///`(example: @Veni Ki MyV3nu3SyncShell)`.
        /// </summary>
        internal static string AskForMarePasswordMessage {
            get {
                return ResourceManager.GetString("AskForMarePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, what is the **name**? 🙂.
        /// </summary>
        internal static string AskForNameDirectMessage {
            get {
                return ResourceManager.GetString("AskForNameDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, what is the **name**? 🙂
        ///`(example: @Veni Ki Veni&apos;s Mainframe)`.
        /// </summary>
        internal static string AskForNameMessage {
            get {
                return ResourceManager.GetString("AskForNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What **timezone** is the opening in?.
        /// </summary>
        internal static string AskForOpeningTimeZone {
            get {
                return ResourceManager.GetString("AskForOpeningTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! Which opening do you want to cancel? 🥰.
        /// </summary>
        internal static string AskForOpeningToCancel {
            get {
                return ResourceManager.GetString("AskForOpeningToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **open**?
        ///`(example: 6:30pm, 9pm or 1:30am)`.
        /// </summary>
        internal static string AskForOpenTimeDirectMessage {
            get {
                return ResourceManager.GetString("AskForOpenTimeDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **open**?
        ///`(examples: @Veni Ki 6:30pm or @Veni Ki 9pm)`.
        /// </summary>
        internal static string AskForOpenTimeMessage {
            get {
                return ResourceManager.GetString("AskForOpenTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **open** on **{0}**?
        ///`(example: 6:30pm, 9pm or 1:30am)`.
        /// </summary>
        internal static string AskForOpenTimeOnDayDirectMessage {
            get {
                return ResourceManager.GetString("AskForOpenTimeOnDayDirectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **open** on **{0}**?
        ///`(examples: @Veni Ki 6:30pm or @Veni Ki 9pm)`.
        /// </summary>
        internal static string AskForOpenTimeOnDayMessage {
            get {
                return ResourceManager.GetString("AskForOpenTimeOnDayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What **time** is the closing from?.
        /// </summary>
        internal static string AskForTimeOfClosing {
            get {
                return ResourceManager.GetString("AskForTimeOfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What **time** is the opening from?.
        /// </summary>
        internal static string AskForTimeOfOpening {
            get {
                return ResourceManager.GetString("AskForTimeOfOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When is your closing?.
        /// </summary>
        internal static string AskIfClosingIsNowOrLater {
            get {
                return ResourceManager.GetString("AskIfClosingIsNowOrLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your venue have a public **Mare SyncShell**?.
        /// </summary>
        internal static string AskIfHasMareMessage {
            get {
                return ResourceManager.GetString("AskIfHasMareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oki! Do you have a weekly opening schedule?.
        /// </summary>
        internal static string AskIfHasSchedule {
            get {
                return ResourceManager.GetString("AskIfHasSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When is your opening?.
        /// </summary>
        internal static string AskIfOpeningIsNowOrLater {
            get {
                return ResourceManager.GetString("AskIfOpeningIsNowOrLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which **{0}**s of the month are you open?.
        /// </summary>
        internal static string AskWhenInMonthMessage {
            get {
                return ResourceManager.GetString("AskWhenInMonthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, our openings are every 2 weeks.
        /// </summary>
        internal static string DescriptionHasBiweeklySchedule {
            get {
                return ResourceManager.GetString("DescriptionHasBiweeklySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, our openings are on a particular day of every month..
        /// </summary>
        internal static string DescriptionHasMonthlySchedule {
            get {
                return ResourceManager.GetString("DescriptionHasMonthlySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, we don&apos;t have a set schedule.
        /// </summary>
        internal static string DescriptionHasNoSchedule {
            get {
                return ResourceManager.GetString("DescriptionHasNoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, our openings are every week..
        /// </summary>
        internal static string DescriptionHasWeeklySchedule {
            get {
                return ResourceManager.GetString("DescriptionHasWeeklySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! Let me know if you need anything. 💕 .
        /// </summary>
        internal static string Dismissed {
            get {
                return ResourceManager.GetString("Dismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaaah. You&apos;ll need to [create a ticket](https://discord.com/channels/942536163959406632/1188579990271434883) and ask staff in the FFXIV Venues discord to change this part of your venue information. 😊.
        /// </summary>
        internal static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaaah, that&apos;s a long opening. 😢 Please only gives hours your are **actively present or staffed**. If you are indeed open and staffed longer than 7 hours please [create a ticket](https://discord.com/channels/942536163959406632/1188579990271434883) in the FFXIV Venues discord to extend for longer hours..
        /// </summary>
        internal static string OpeningTooLong {
            get {
                return ResourceManager.GetString("OpeningTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biweekly.
        /// </summary>
        internal static string OptionBiweekly {
            get {
                return ResourceManager.GetString("OptionBiweekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string OptionMonthly {
            get {
                return ResourceManager.GetString("OptionMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedule.
        /// </summary>
        internal static string OptionNoSchedule {
            get {
                return ResourceManager.GetString("OptionNoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string OptionWeekly {
            get {
                return ResourceManager.GetString("OptionWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which venue would you like to edit? 🤔.
        /// </summary>
        internal static string SelectVenueToEdit {
            get {
                return ResourceManager.GetString("SelectVenueToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay! I&apos;ve cancelled the closure! 🥰.
        /// </summary>
        internal static string VenueClosureCancelled {
            get {
                return ResourceManager.GetString("VenueClosureCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay! I&apos;ve removed your closure status. Welcome back! ♥️.
        /// </summary>
        internal static string VenueClosureEnded {
            get {
                return ResourceManager.GetString("VenueClosureEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! I&apos;ll lock up! I can&apos;t wait til we reopen. 🥰.
        /// </summary>
        internal static string VenueNowClosed {
            get {
                return ResourceManager.GetString("VenueNowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay! You&apos;re glowing pink on the index. Let&apos;s have fun today! ♥️.
        /// </summary>
        internal static string VenueNowOpen {
            get {
                return ResourceManager.GetString("VenueNowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay! I&apos;ve cancelled the opening. 🥲.
        /// </summary>
        internal static string VenueOpeningCancelled {
            get {
                return ResourceManager.GetString("VenueOpeningCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! All closed up, I hope you had fun! ♥️.
        /// </summary>
        internal static string VenueOpeningEnded {
            get {
                return ResourceManager.GetString("VenueOpeningEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooo! We&apos;re all set. I can&apos;t wait! ♥️.
        /// </summary>
        internal static string VenueOpenLater {
            get {
                return ResourceManager.GetString("VenueOpenLater", resourceCulture);
            }
        }
    }
}
