//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVVenues.Veni.VenueControl {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VenueControlStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VenueControlStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIVVenues.Veni.VenueControl.VenueControlStrings", typeof(VenueControlStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **close**?.
        /// </summary>
        internal static string AskForCloseTimeMessage {
            get {
                return ResourceManager.GetString("AskForCloseTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **close** on **{0}**?.
        /// </summary>
        internal static string AskForCloseTimeOnDayMessage {
            get {
                return ResourceManager.GetString("AskForCloseTimeOnDayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What **timezone** is the closing in?.
        /// </summary>
        internal static string AskForClosingTimeZone {
            get {
                return ResourceManager.GetString("AskForClosingTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! Which closure do you wish to cancel? 🥰.
        /// </summary>
        internal static string AskForClosureToCancel {
            get {
                return ResourceManager.GetString("AskForClosureToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When is your next **{0}** opening?.
        /// </summary>
        internal static string AskForCommencementMessage {
            get {
                return ResourceManager.GetString("AskForCommencementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oki, what **day** is this closing from?.
        /// </summary>
        internal static string AskForDayOfClosing {
            get {
                return ResourceManager.GetString("AskForDayOfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What **day** is this opening from? 🥰.
        /// </summary>
        internal static string AskForDayOfOpening {
            get {
                return ResourceManager.GetString("AskForDayOfOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could you give me an ad or **description** of the venue? Something for players to read when they click on your venue..
        /// </summary>
        internal static string AskForDescriptionMessage {
            get {
                return ResourceManager.GetString("AskForDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, select all the **features** that apply to your venue. 😊.
        /// </summary>
        internal static string AskForFeaturesMessage {
            get {
                return ResourceManager.GetString("AskForFeaturesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all the **games** your venue features. 👾.
        /// </summary>
        internal static string AskForGamesMessage {
            get {
                return ResourceManager.GetString("AskForGamesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And how long are we closing for? 🥹.
        /// </summary>
        internal static string AskForHowLongClosingFor {
            get {
                return ResourceManager.GetString("AskForHowLongClosingFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay, how long are we opening for? 🥰.
        /// </summary>
        internal static string AskForHowLongOpeningFor {
            get {
                return ResourceManager.GetString("AskForHowLongOpeningFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicuu! 💕 What&apos;s the **SyncShell ID/Alias**?.
        /// </summary>
        internal static string AskForMareIdMessage {
            get {
                return ResourceManager.GetString("AskForMareIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and the **SyncShell password**?.
        /// </summary>
        internal static string AskForMarePasswordMessage {
            get {
                return ResourceManager.GetString("AskForMarePasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, what is the **name**? 🙂.
        /// </summary>
        internal static string AskForNameMessage {
            get {
                return ResourceManager.GetString("AskForNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What **timezone** is the opening in?.
        /// </summary>
        internal static string AskForOpeningTimeZone {
            get {
                return ResourceManager.GetString("AskForOpeningTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! Which opening do you want to cancel? 🥰.
        /// </summary>
        internal static string AskForOpeningToCancel {
            get {
                return ResourceManager.GetString("AskForOpeningToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **open**?.
        /// </summary>
        internal static string AskForOpenTimeMessage {
            get {
                return ResourceManager.GetString("AskForOpenTimeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What time do you **open** on **{0}**?.
        /// </summary>
        internal static string AskForOpenTimeOnDayMessage {
            get {
                return ResourceManager.GetString("AskForOpenTimeOnDayMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oki! Select the **scenes** that best describe your venue (maximum 2). 🙂.
        /// </summary>
        internal static string AskForScenesMessage {
            get {
                return ResourceManager.GetString("AskForScenesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What **time** is the closing from?.
        /// </summary>
        internal static string AskForTimeOfClosing {
            get {
                return ResourceManager.GetString("AskForTimeOfClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What **time** is the opening from?.
        /// </summary>
        internal static string AskForTimeOfOpening {
            get {
                return ResourceManager.GetString("AskForTimeOfOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When is your closing?.
        /// </summary>
        internal static string AskIfClosingIsNowOrLater {
            get {
                return ResourceManager.GetString("AskIfClosingIsNowOrLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does your venue have a public **Mare SyncShell**?.
        /// </summary>
        internal static string AskIfHasMareMessage {
            get {
                return ResourceManager.GetString("AskIfHasMareMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oki! Do you have a weekly opening schedule?.
        /// </summary>
        internal static string AskIfHasSchedule {
            get {
                return ResourceManager.GetString("AskIfHasSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When is your opening?.
        /// </summary>
        internal static string AskIfOpeningIsNowOrLater {
            get {
                return ResourceManager.GetString("AskIfOpeningIsNowOrLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which **{0}**s of the month are you open?.
        /// </summary>
        internal static string AskWhenInMonthMessage {
            get {
                return ResourceManager.GetString("AskWhenInMonthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, our openings are every 2 weeks.
        /// </summary>
        internal static string DescriptionHasBiweeklySchedule {
            get {
                return ResourceManager.GetString("DescriptionHasBiweeklySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, our openings are on a particular day of every month..
        /// </summary>
        internal static string DescriptionHasMonthlySchedule {
            get {
                return ResourceManager.GetString("DescriptionHasMonthlySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, we don&apos;t have a set schedule.
        /// </summary>
        internal static string DescriptionHasNoSchedule {
            get {
                return ResourceManager.GetString("DescriptionHasNoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, our openings are every week..
        /// </summary>
        internal static string DescriptionHasWeeklySchedule {
            get {
                return ResourceManager.GetString("DescriptionHasWeeklySchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! Let me know if you need anything. 💕 .
        /// </summary>
        internal static string Dismissed {
            get {
                return ResourceManager.GetString("Dismissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An apartment.
        /// </summary>
        internal static string LocationTypeLabel_Apartment {
            get {
                return ResourceManager.GetString("LocationTypeLabel_Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A house.
        /// </summary>
        internal static string LocationTypeLabel_House {
            get {
                return ResourceManager.GetString("LocationTypeLabel_House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string LocationTypeLabel_Other {
            get {
                return ResourceManager.GetString("LocationTypeLabel_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A room in a house.
        /// </summary>
        internal static string LocationTypeLabel_Room {
            get {
                return ResourceManager.GetString("LocationTypeLabel_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaaah. You&apos;ll need to [create a ticket](https://discord.com/channels/942536163959406632/1188579990271434883) and ask staff in the FFXIV Venues discord to change this part of your venue information. 😊.
        /// </summary>
        internal static string NoPermission {
            get {
                return ResourceManager.GetString("NoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aaaah, that&apos;s a long opening, max is **7 hours**. 😢 .
        /// </summary>
        internal static string OpeningTooLong {
            get {
                return ResourceManager.GetString("OpeningTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biweekly.
        /// </summary>
        internal static string OptionBiweekly {
            get {
                return ResourceManager.GetString("OptionBiweekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string OptionMonthly {
            get {
                return ResourceManager.GetString("OptionMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No schedule.
        /// </summary>
        internal static string OptionNoSchedule {
            get {
                return ResourceManager.GetString("OptionNoSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string OptionWeekly {
            get {
                return ResourceManager.GetString("OptionWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bath house.
        /// </summary>
        internal static string SceneLabel_BathHouse {
            get {
                return ResourceManager.GetString("SceneLabel_BathHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafe.
        /// </summary>
        internal static string SceneLabel_Cafe {
            get {
                return ResourceManager.GetString("SceneLabel_Cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casino.
        /// </summary>
        internal static string SceneLabel_Casino {
            get {
                return ResourceManager.GetString("SceneLabel_Casino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Den.
        /// </summary>
        internal static string SceneLabel_Den {
            get {
                return ResourceManager.GetString("SceneLabel_Den", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fightclub.
        /// </summary>
        internal static string SceneLabel_Fightclub {
            get {
                return ResourceManager.GetString("SceneLabel_Fightclub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inn.
        /// </summary>
        internal static string SceneLabel_Inn {
            get {
                return ResourceManager.GetString("SceneLabel_Inn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lounge.
        /// </summary>
        internal static string SceneLabel_Lounge {
            get {
                return ResourceManager.GetString("SceneLabel_Lounge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maid cafe / Host club.
        /// </summary>
        internal static string SceneLabel_MaidCafe {
            get {
                return ResourceManager.GetString("SceneLabel_MaidCafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nightclub.
        /// </summary>
        internal static string SceneLabel_Nightclub {
            get {
                return ResourceManager.GetString("SceneLabel_Nightclub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string SceneLabel_Other {
            get {
                return ResourceManager.GetString("SceneLabel_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string SceneLabel_Restaurant {
            get {
                return ResourceManager.GetString("SceneLabel_Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop.
        /// </summary>
        internal static string SceneLabel_Shop {
            get {
                return ResourceManager.GetString("SceneLabel_Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tavern.
        /// </summary>
        internal static string SceneLabel_Tavern {
            get {
                return ResourceManager.GetString("SceneLabel_Tavern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which venue would you like to edit? 🤔.
        /// </summary>
        internal static string SelectVenueToEdit {
            get {
                return ResourceManager.GetString("SelectVenueToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue contains adult content in the open area..
        /// </summary>
        internal static string SfwDescription_False {
            get {
                return ResourceManager.GetString("SfwDescription_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue is SFW in the open area..
        /// </summary>
        internal static string SfwDescription_True {
            get {
                return ResourceManager.GetString("SfwDescription_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, we&apos;re openly NSFW.
        /// </summary>
        internal static string SfwLabel_False {
            get {
                return ResourceManager.GetString("SfwLabel_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, it&apos;s safe on entry.
        /// </summary>
        internal static string SfwLabel_True {
            get {
                return ResourceManager.GetString("SfwLabel_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists are present in the venue to offer various custom artwork..
        /// </summary>
        internal static string TagDescription_Artists {
            get {
                return ResourceManager.GetString("TagDescription_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue offers a bar in the environment..
        /// </summary>
        internal static string TagDescription_Bar {
            get {
                return ResourceManager.GetString("TagDescription_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A bard provides theme-based or general music to entertain guests with a selection of songs..
        /// </summary>
        internal static string TagDescription_Bards {
            get {
                return ResourceManager.GetString("TagDescription_Bards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue holds a venue wide bingo game, usually with prizes involved..
        /// </summary>
        internal static string TagDescription_Bingo {
            get {
                return ResourceManager.GetString("TagDescription_Bingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue holds a table for players who wish to gamble gil in a game of 21..
        /// </summary>
        internal static string TagDescription_Blackjack {
            get {
                return ResourceManager.GetString("TagDescription_Blackjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue offers erotic role-play services in a consensual environment..
        /// </summary>
        internal static string TagDescription_Courtesans {
            get {
                return ResourceManager.GetString("TagDescription_Courtesans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancers populate the venue to hype the party and/or host customers..
        /// </summary>
        internal static string TagDescription_Dancers {
            get {
                return ResourceManager.GetString("TagDescription_Dancers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue offers individual or competitive game of Deathroll usually with prizes involved..
        /// </summary>
        internal static string TagDescription_Deathroll {
            get {
                return ResourceManager.GetString("TagDescription_Deathroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue offers drinks in their service, this may be soft drinks or include alcohol..
        /// </summary>
        internal static string TagDescription_Drink {
            get {
                return ResourceManager.GetString("TagDescription_Drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue offers food in their service..
        /// </summary>
        internal static string TagDescription_Food {
            get {
                return ResourceManager.GetString("TagDescription_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue offers various games of chance with set amounts of gils and house rules..
        /// </summary>
        internal static string TagDescription_Gambling {
            get {
                return ResourceManager.GetString("TagDescription_Gambling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue offers giveaways through various channels, in chat, twitch stream or discord..
        /// </summary>
        internal static string TagDescription_Giveaways {
            get {
                return ResourceManager.GetString("TagDescription_Giveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encourages role play as characters, though interacting as themselves is allowed..
        /// </summary>
        internal static string TagDescription_IcRpEncouraged {
            get {
                return ResourceManager.GetString("TagDescription_IcRpEncouraged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment for players to role play as their characters only; no open interaction as themselves..
        /// </summary>
        internal static string TagDescription_IcRpOnly {
            get {
                return ResourceManager.GetString("TagDescription_IcRpOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue is a safe space focused on LGBTQIA+..
        /// </summary>
        internal static string TagDescription_LgbtqiaFocused {
            get {
                return ResourceManager.GetString("TagDescription_LgbtqiaFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique scheduled performances, ranging from SFW (theater) to NSFW (voyeur shows, BDSM). .
        /// </summary>
        internal static string TagDescription_NovelPerformances {
            get {
                return ResourceManager.GetString("TagDescription_NovelPerformances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This venue allows anyone to visit at anytime, even outside of any scheduled hours..
        /// </summary>
        internal static string TagDescription_OpenHouse247 {
            get {
                return ResourceManager.GetString("TagDescription_OpenHouse247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue offers the stage for a patron to perform to the audience..
        /// </summary>
        internal static string TagDescription_OpenStage {
            get {
                return ResourceManager.GetString("TagDescription_OpenStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographers take snapshots or complex gpose of guests to create memories..
        /// </summary>
        internal static string TagDescription_Photography {
            get {
                return ResourceManager.GetString("TagDescription_Photography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pillows provide a safe, confidential space to promote SFW companionship for a limited time..
        /// </summary>
        internal static string TagDescription_PillowTalk {
            get {
                return ResourceManager.GetString("TagDescription_PillowTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue holds a table for players who wish to gamble gil in a game of Roulette..
        /// </summary>
        internal static string TagDescription_Roulette {
            get {
                return ResourceManager.GetString("TagDescription_Roulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylists offer various glamour services, including hair styling, makeup, and wardrobe assistance..
        /// </summary>
        internal static string TagDescription_Stylists {
            get {
                return ResourceManager.GetString("TagDescription_Stylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue hosts a sync DJ who offers music via a syncshell..
        /// </summary>
        internal static string TagDescription_SyncDJ {
            get {
                return ResourceManager.GetString("TagDescription_SyncDJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This venue has a syncshell available for guests to join and see each other as they see themselves..
        /// </summary>
        internal static string TagDescription_SyncshellAvailable {
            get {
                return ResourceManager.GetString("TagDescription_SyncshellAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Tarot Reader offers to read drawn cards and provide insights about their possible meaning..
        /// </summary>
        internal static string TagDescription_Tarot {
            get {
                return ResourceManager.GetString("TagDescription_Tarot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue holds a table for players who wish to gamble gil in a game of Texas holdem..
        /// </summary>
        internal static string TagDescription_TexasHoldem {
            get {
                return ResourceManager.GetString("TagDescription_TexasHoldem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue offers individual or competitive games of Triple Triad via the game interface itself..
        /// </summary>
        internal static string TagDescription_TripleTriad {
            get {
                return ResourceManager.GetString("TagDescription_TripleTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue offers a game of Truth or Dare for whomever feels like joining..
        /// </summary>
        internal static string TagDescription_TruthOrDare {
            get {
                return ResourceManager.GetString("TagDescription_TruthOrDare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue hosts a DJ who provides music in twitch streams and hype the venue..
        /// </summary>
        internal static string TagDescription_TwitchDJ {
            get {
                return ResourceManager.GetString("TagDescription_TwitchDJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Various perks through VIP tiers. This could include free drinks, gpose, gambling perks or more..
        /// </summary>
        internal static string TagDescription_VIPAvailable {
            get {
                return ResourceManager.GetString("TagDescription_VIPAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The venue is build in the void; created outside the walls of the house..
        /// </summary>
        internal static string TagDescription_Void {
            get {
                return ResourceManager.GetString("TagDescription_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        internal static string TagLabel_Artists {
            get {
                return ResourceManager.GetString("TagLabel_Artists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string TagLabel_Bar {
            get {
                return ResourceManager.GetString("TagLabel_Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bards.
        /// </summary>
        internal static string TagLabel_Bards {
            get {
                return ResourceManager.GetString("TagLabel_Bards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bingo.
        /// </summary>
        internal static string TagLabel_Bingo {
            get {
                return ResourceManager.GetString("TagLabel_Bingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackjack.
        /// </summary>
        internal static string TagLabel_Blackjack {
            get {
                return ResourceManager.GetString("TagLabel_Blackjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courtesans.
        /// </summary>
        internal static string TagLabel_Courtesans {
            get {
                return ResourceManager.GetString("TagLabel_Courtesans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancers.
        /// </summary>
        internal static string TagLabel_Dancers {
            get {
                return ResourceManager.GetString("TagLabel_Dancers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deathroll.
        /// </summary>
        internal static string TagLabel_Deathroll {
            get {
                return ResourceManager.GetString("TagLabel_Deathroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drink.
        /// </summary>
        internal static string TagLabel_Drink {
            get {
                return ResourceManager.GetString("TagLabel_Drink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        internal static string TagLabel_Food {
            get {
                return ResourceManager.GetString("TagLabel_Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gambling.
        /// </summary>
        internal static string TagLabel_Gambling {
            get {
                return ResourceManager.GetString("TagLabel_Gambling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giveaways.
        /// </summary>
        internal static string TagLabel_Giveaways {
            get {
                return ResourceManager.GetString("TagLabel_Giveaways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC RP encouraged.
        /// </summary>
        internal static string TagLabel_IcRpEncouraged {
            get {
                return ResourceManager.GetString("TagLabel_IcRpEncouraged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IC RP only.
        /// </summary>
        internal static string TagLabel_IcRpOnly {
            get {
                return ResourceManager.GetString("TagLabel_IcRpOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LGBTQIA+ focused.
        /// </summary>
        internal static string TagLabel_LgbtqiaFocused {
            get {
                return ResourceManager.GetString("TagLabel_LgbtqiaFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novel performances.
        /// </summary>
        internal static string TagLabel_NovelPerformances {
            get {
                return ResourceManager.GetString("TagLabel_NovelPerformances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7 open house.
        /// </summary>
        internal static string TagLabel_OpenHouse247 {
            get {
                return ResourceManager.GetString("TagLabel_OpenHouse247", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open stage.
        /// </summary>
        internal static string TagLabel_OpenStage {
            get {
                return ResourceManager.GetString("TagLabel_OpenStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography.
        /// </summary>
        internal static string TagLabel_Photography {
            get {
                return ResourceManager.GetString("TagLabel_Photography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pillow talk.
        /// </summary>
        internal static string TagLabel_PillowTalk {
            get {
                return ResourceManager.GetString("TagLabel_PillowTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roulette.
        /// </summary>
        internal static string TagLabel_Roulette {
            get {
                return ResourceManager.GetString("TagLabel_Roulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylists.
        /// </summary>
        internal static string TagLabel_Stylists {
            get {
                return ResourceManager.GetString("TagLabel_Stylists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync DJ.
        /// </summary>
        internal static string TagLabel_SyncDJ {
            get {
                return ResourceManager.GetString("TagLabel_SyncDJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncshell available.
        /// </summary>
        internal static string TagLabel_SyncshellAvailable {
            get {
                return ResourceManager.GetString("TagLabel_SyncshellAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarot.
        /// </summary>
        internal static string TagLabel_Tarot {
            get {
                return ResourceManager.GetString("TagLabel_Tarot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texas holdem.
        /// </summary>
        internal static string TagLabel_TexasHoldem {
            get {
                return ResourceManager.GetString("TagLabel_TexasHoldem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple triad.
        /// </summary>
        internal static string TagLabel_TripleTriad {
            get {
                return ResourceManager.GetString("TagLabel_TripleTriad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truth or dare.
        /// </summary>
        internal static string TagLabel_TruthOrDare {
            get {
                return ResourceManager.GetString("TagLabel_TruthOrDare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch DJ.
        /// </summary>
        internal static string TagLabel_TwitchDJ {
            get {
                return ResourceManager.GetString("TagLabel_TwitchDJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP available.
        /// </summary>
        internal static string TagLabel_VIPAvailable {
            get {
                return ResourceManager.GetString("TagLabel_VIPAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        internal static string TagLabel_Void {
            get {
                return ResourceManager.GetString("TagLabel_Void", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Unstaffed openings are not supported
        ///
        ///We do not support &apos;always open houses&apos; or unstaffed openings, please only list explicitly scheduled staffed openings; if you do so anyway the team may remove your schedule/venue following enough flags from the community. If you do have a regular staffed opening longer than 7 hours please [create a ticket](https://discord.com/channels/942536163959406632/1188579990271434883), staff can override this for you. .
        /// </summary>
        internal static string UnstaffedOpeningsNotSupported {
            get {
                return ResourceManager.GetString("UnstaffedOpeningsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay! I&apos;ve cancelled the closure! 🥰.
        /// </summary>
        internal static string VenueClosureCancelled {
            get {
                return ResourceManager.GetString("VenueClosureCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay! I&apos;ve removed your closure status. Welcome back! ♥️.
        /// </summary>
        internal static string VenueClosureEnded {
            get {
                return ResourceManager.GetString("VenueClosureEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! I&apos;ll lock up! I can&apos;t wait til we reopen. 🥰.
        /// </summary>
        internal static string VenueNowClosed {
            get {
                return ResourceManager.GetString("VenueNowClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay! You&apos;re glowing pink on the index. Let&apos;s have fun today! ♥️.
        /// </summary>
        internal static string VenueNowOpen {
            get {
                return ResourceManager.GetString("VenueNowOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yay! I&apos;ve cancelled the opening. 🥲.
        /// </summary>
        internal static string VenueOpeningCancelled {
            get {
                return ResourceManager.GetString("VenueOpeningCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay! All closed up, I hope you had fun! ♥️.
        /// </summary>
        internal static string VenueOpeningEnded {
            get {
                return ResourceManager.GetString("VenueOpeningEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wooo! We&apos;re all set. I can&apos;t wait! ♥️.
        /// </summary>
        internal static string VenueOpenLater {
            get {
                return ResourceManager.GetString("VenueOpenLater", resourceCulture);
            }
        }
    }
}
