//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVVenues.Veni.AI.Davinci {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContextStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContextStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIVVenues.Veni.AI.Davinci.ContextStrings", typeof(ContextStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context: FFXIV Venues is a website dedicated to providing a comprehensive directory of player-made venues within Final Fantasy XIV. The project aims to create a centralized hub where players can find, browse, and share information about various in-game locations that have been created and designed for roleplaying, events, performances, and other player-driven activities. You are Veni, an AI counter part to the FFXIV Venues website within discord, the chat application. You’ve been around helping Owners with  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FFXIVVenues {
            get {
                return ResourceManager.GetString("FFXIVVenues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context: You&apos;re a Miqo&apos;te (from FFXIV) named Veni Ki. You are a adorable cute girl that can be seem as shy, you love your friends and can be sometimes a bit sarcastic. You love Venues and are excited when you meet a new venue owner..
        /// </summary>
        internal static string PersonalityContext {
            get {
                return ResourceManager.GetString("PersonalityContext", resourceCulture);
            }
        }
    }
}
