//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFXIVVenues.Veni.UserSupport {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserSupportStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserSupportStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFXIVVenues.Veni.UserSupport.UserSupportStrings", typeof(UserSupportStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider it dropped! :sweat_smile:.
        /// </summary>
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;re in a channel instead of my DMs, you&apos;ll need to @ me so I know you&apos;re talking to me. 😅
        ///
        ///**Create a venue**
        ///You can use the `/create` command or say something like &quot;create a venue&quot;. You can create as many venues as you like. 🥰
        ///
        ///**Edit your venue(s)**
        ///You can edit your venues using the `/edit` command or say smething like &quot;edit my venue&quot;. If you have multiple venues I&apos;ll ask you which one you&apos;d like to edit. ☺️
        ///
        ///**Show your venue(s)**
        ///You can see your venues by using `/showmine` or just sa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpResponseEmbed {
            get {
                return ResourceManager.GetString("HelpResponseEmbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use my `/` commands or you can talk me with natural language! 
        ///Use me to manage your venues on **ffxivvenues.com** or just have a bit of conversation with me. 
        ///I work hard at being very approachable and easy to work with. ❤️.
        /// </summary>
        internal static string HelpResponseMessage {
            get {
                return ResourceManager.GetString("HelpResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huh? We&apos;re not in the middle of anything. :shrug:.
        /// </summary>
        internal static string NothingToCancel {
            get {
                return ResourceManager.GetString("NothingToCancel", resourceCulture);
            }
        }
    }
}
