name: Build and publish Veni's docker image

on:
  push:
    branches:
      - master

jobs:
  build and publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build docker image
        run: docker build ./ -t ${{ secrets.DOCKER_USERNAME }}/ffxivvenues.veni:latest --build-arg NUGET_REPO_PASSWORD=${{ secrets.NUGET_REPO_PASSWORD }}

      - name: Push docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ffxivvenues.veni:latest