name: Build and publish Veni's docker image

on:
  push:
    branches:
      - uat

jobs:
  build_and_publish:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Build and push docker image
        run: |
          docker buildx create --name ffxivvenues-builder --driver docker-container --bootstrap --use
          docker buildx build --push --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/ffxivvenues.veni:uat ./
